### ISSUE TITLE
Save mission

### ISSUE THREAD

**Issue by shifenis** [Benargeez/SSPCM#12]
When I activate this mod, and playing Career Missions, I unable to save.

[This is the screen of the menu](https://imgur.com/zkSwJHA)

As you can see in the image, the save button is disabled. 
It is opportune to save the game even with the mod active.

**Comment by Benargee** [comment]
This is not a feature I added with SSPCM. There are some missions or some difficulty settings that prevent frequent mission saving. Please confirm that is not the case before resuming this report. Closing until you come back with a stronger case.
