### ISSUE TITLE
Zeus Not Working on Dedicated Server

### ISSUE THREAD

**Issue by Glitch58** [Benargeez/SSPCM#16]
I run a small dedicated server with a group of friends. We all use your mod for teleportation when necessary and to spawn vehicles in long missions, it's one of our favorite mods, thank you for making it.. However, since moving to a dedicated server, I have been unable to access the Zeus function. I am the server admin, the server has the mod installed as well as all players. Any thoughts, ideas, solutions?

**Comment by Benargee** [comment]
Mod not intended to support multiplayer. Maybe one day with server admin permissions.
