### ISSUE TITLE
new link please

### ISSUE THREAD

**Issue by mokam1** [Benargeez/SSPCM#22]
i want a link to download the sspcm mod steam isn't working with me please help me with a another link like google drive or anything

**Comment by xelantro** [comment]
You can download any mod as zip here https://steamworkshopdownloader.io/
(link to sspcm on steam: https://steamcommunity.com/sharedfiles/filedetails/?id=410206202)

**Comment by Benargee** [comment]
It seems like the Google Drive direct download link doesn't work well anymore (~~https://docs.google.com/uc?id=0B_Vk9SZQLiNtTk5lVEZiY1hSS0k&export=download~~)
Just going to have people use the link https://drive.google.com/file/d/0B_Vk9SZQLiNtTk5lVEZiY1hSS0k/view?usp=sharing&resourcekey=0-HgmQteJrRq5iYK9GGsKcvQ
It seems like you still have to be logged in to Google for it to work.

**Comment by Benargee** [comment]
#21 Same Issue

**Comment by Benargee** [comment]
Updated [forum](https://forums.bohemia.net/forums/topic/179688-simple-single-player-cheat-menu/) download link . Marking as closed for now.
